# Generated by Django 4.1.7 on 2023-02-26 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_staff_delete_student_delete_teacher'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Staff',
            new_name='Teacher',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='staff',
            new_name='teacher',
        ),
    ]
